#framework:
 #   messenger:
  #      transports:
    #        product_async:
   #             dsn: 'amqp://user:password@127.0.0.1:5672/%2f/'
     #           options:
      #              exchange:
       #                 name: 'product_queue'
        #    order_async:
         #       dsn: 'amqp://user:password@127.0.0.1:5672/%2f/'
          #      options:
           #         exchange:
            #            name: 'order_queue'
        #routing:
         #   'SharedMessages\Message\ProductMessage': order_async
          #  'SharedMessages\Message\OrderMessage': product_async
           # 'SharedMessages\Message\CompleteOrderMessage': order_async